### ISSUE TITLE
Add possibility to pass 'unused' option to Terser

### ISSUE THREAD

**Issue by roberthovsepyan** [gravity-ui/app-builder#121]
Terser.js has weird behaviour with certain libraries that produces invalid code. Namely, [antlr4ng](https://github.com/mike-lischke/antlr4ng) and [antlr4-c3](https://github.com/mike-lischke/antlr4-c3). When having these packages as dependencies in the project, terser minification results in code that throws runtime error. However if we pass `unused: false` to terserOptions, this bug goes away. Like so
```
terserOptions: {
    compress: {
        passes: 2,
        unused: false,
    },
}
```

Currently we can extend our webpack configuration, however a cleaner way to do this would be nice
```
  webpack: (config) => ({
                ...config,
                optimization: {
                    ...config.optimization,
                    minimizer: [
                        config.optimization?.minimizer[0],
                        (compiler) => {
                            new TerserPlugin({
                                terserOptions: {
                                    compress: {
                                        passes: 2,
                                        unused: false,
                                    },
                                    mangle: true,
                                },
                            }).apply(compiler);
                        },
                    ],
                },
            }),
```

**Comment by ValeraS** [comment]
Can you please provide a repo with reproduction?

**Comment by roberthovsepyan** [comment]
> Can you please provide a repo with reproduction?

Don't really have a public repo with reproduction currently, but if you install antlr4ng or antlr4-c3 package in any project that uses app-builder, and then build it and try to run it, you'll see the bug

If that's not good enough, I'll try to create such a repo
