### ISSUE TITLE
contextReplacement['highlight.js'] doesn't work as expected

### ISSUE THREAD

**Issue by dsleepo** [gravity-ui/app-builder#139]
In the ﻿app-builder.config.ts, I have specified the following configuration:
```
contextReplacement: {
  'highlight.js': ['bash'],
},
```
But other languages, such as ﻿`node_modules/highlight.js/lib/languages/1c.js`, have included in the bundle.

Demo: https://stackblitz.com/edit/stackblitz-starters-ug5coj?file=package.json

![2024-05-17_18-20-44](https://github.com/gravity-ui/app-builder/assets/827806/782f674a-2890-4ad5-9a13-efc4c2c149bd)

**Comment by ValeraS** [comment]
This settings is more applicable if you use libraries what use `highlight.js` under the hood, like `react-highlight`. If you use `highlight.js` yourself and know what languages will be used, load it as `highlight.js` [documentation ](https://highlightjs.org/#usage) recommends:

```js
// Using ES6 import syntax
import hljs from 'highlight.js/lib/core';
import javascript from 'highlight.js/lib/languages/javascript';

// Then register the languages you need
hljs.registerLanguage('javascript', javascript);
```

`ContexReplacementPlugin` works only for dynamic requires like `require('highlight.js/lib/languages/' + lang)`. For example, look how `highlight.js` is used in `react-highlight` https://github.com/akiran/react-highlight/blob/c180f6cdf62833c41a15a86392790d762e8a6305/src/optimized.js#L22
